### ISSUE TITLE
3.4.1操作指示符  看不懂怎么计算的？?

### ISSUE THREAD

**Issue by lanfairy** [JessonYue/Computer-basics#1]
<img width="526" alt="图3-3" src="https://user-images.githubusercontent.com/13324711/83506198-682fda80-a4f9-11ea-9820-007297e19f17.png">

**Comment by JessonYue** [comment]
这里的知识涉及到汇编，而汇编往往和硬件很有关系，比如X86或者ARM的指令是不一样的。这张图我们需要理解几个概念：
1.汇编中出现的数据有立即数（**$52、$0x11等**）、寄存器里面的数据。【上图是用Ea来表示任意寄存器a,用引用 R[Ea]来表示它的值。】存储器里面的数据（可以理解很大的字节数组）。
2.比如最后1行的存储器 Imm（r,r,s）,我们可以这样解读
Imm 是立即偏移数、Eb 是基址寄存器、Ei 是变址寄存器、s 是比例因子，必须是 1、2、4或8
那么在汇编中 我们可以看到2(%esp,%eax,4)这个操作数的意思是：地址为2+%esp+4*%eax的存储器区域的值。

所以你应该明白这张表的意思 表达的就是在底层最为重要的offset。也就是指针偏移，这张表对应的是X86的汇编格式，针对ARM是不一样的，具体可以查ARM的汇编指令。暂时了解这个概念就可以了，ARM指令我们暂时不做逆向，可以不要花太多精力。加油 @lanfairy
