### ISSUE TITLE
《深入理解计算机系统》第一章 1.7.1 进程——进程上下文切换概念问题

### ISSUE THREAD

**Issue by xt4665699** [JessonYue/Computer-basics#11]
学科：《深入理解计算机系统》
类型：知识理解
内容：该书中1.7. 1 进程中对上文切换的定义。我以前在听一些工开课的时候，在讲多线程的时候，说是线程之间的切换叫做上下文切换，但是书中说是进程之间的切换是上下文切换，这两个上下文切换是一个概念吗。在就是线程不是运行在进程当中吗，如果同一个进程中的线程切换难道没有上下文切换的概念吗，虽然是同一进程的线程互相切换也得有消耗吧。

![image](https://user-images.githubusercontent.com/19283693/83622026-0dae8100-a5c2-11ea-9c2f-a71a69314968.png)

**Comment by empty56631** [comment]
进程切换和线程切换都需要切换上下文，进程切换的是进程上下文，线程切换的是线程上下文
进程和线程的区别在于内存空间不同，每个进程都有自己独立的进程空间，而线程的内存空间是共享的，线程属于进程的一部分，进程可以访问系统资源，线程不能访问系统资源但是可以访问进程资源
线程切换比进程切换速度，开销小
以上是我的理解，如有不对还望指出

**Comment by JessonYue** [comment]
参考资料：
http://www.gnu.org/software/pth/  内核之上的线程库
以Linux的pthread为例，它的一个线程，在内核里和进程是同样的调度单位，我们要搞清楚上下文是什么？

主要是进程的状态的保存和寄存器的状态。都是在内核层面的struct 具体可以看linux内核的部分（sched.h）
R(task_running) : 可执行状态
S (task_interruptible): 可中断的睡眠状态
D (task_uninterruptible): 不可中断的睡眠状态
T (task_stopped or task_traced): 暂停状态或跟踪状态
Z (task_dead - exit_zombie): 退出状态,进程成为僵尸进程
X (task_dead - exit_dead): 退出状态,进程即将被销毁

**Comment by JessonYue** [comment]
好问题 后期我会直播重点讲 先了解到这个程度
