### ISSUE TITLE
C语言中TMin32的表示

### ISSUE THREAD

**Issue by slowhandwc** [JessonYue/Computer-basics#12]
C语言中TMin32 要写成-2147483647-1，而不是-2147483648，为什么？

**Comment by JessonYue** [comment]
参见 http://csapp.cs.cmu.edu/public/waside/waside-tmin.pdf 

总结：
虽然-2147483648 这个数值能够用int类型来表示，但在C语言中却没法写出对应这个数值的int类型常量。
