### ISSUE TITLE
《深入理解计算机系统》第二章 2.1.2 字节数大小--虚拟地址空间的概念问题

### ISSUE THREAD

**Issue by SinglerZhou** [JessonYue/Computer-basics#13]
虚拟地址空间是什么意思？32位字长限制虚拟地址空间为4GB，这个“虚拟地址空间”是不是我们说的内存条，理解为"32位计算机运行内存最大限制为4GB"是否正确？

**Comment by JessonYue** [comment]
物理地址空间是实实在在存在于计算机中，并且对于每一台计算机来说只有一个。
虚拟地址空间是指虚拟的、人们想象出来的地址空间，它实际并不存在。每个进程都有自己独立的虚拟空间，而且每个进程只能访问自己的地址空间。(做到了进程的隔离)

2的32次方 对应的是0-4G，那么其中有1G的内核空间，这个问题暂时这么理解，后面要看linux内核才能彻底搞定，内存的管理的原理
