### ISSUE TITLE
C语言中的指针和Java中的对象引用有没有本质的关联？

### ISSUE THREAD

**Issue by guangzq** [JessonYue/Computer-basics#14]
学科：《深入理解计算机系统》
类型：知识理解
内容：C语言中的指针和Java中的对象引用有没有本质的关联

**Comment by itzuo** [comment]
没有关联，指针更强大，可以直接修改值

**Comment by JessonYue** [comment]
一个对象如果没有任何指针指向它，这个对象就称为垃圾对象，因为java只能通过指针才能访问对象，没有指针指向的对象将无法使用无法访问，将被java的内存回收机制给回收掉。所以对象和指针在狭义上可以理解成一致的。
