### ISSUE TITLE
第七章 链接问题

### ISSUE THREAD

**Issue by lanfairy** [JessonYue/Computer-basics#15]
C、C++在链接时，链接器是按需复制被程序引用的目标模块，而不是复制整个静态库。哪 在Java和 Android 是怎么操作的？Android 中的 Dalvik 和 ART 虚拟机起到了什么作用？
Android程序是即可以在加载时链接又可以在运行时链接吗？
.a文件是 C，C++，Objective-c的静态库
那 jar 包（一组 class 文件的压缩包）是 Java的 静态库？

**Comment by lanfairy** [comment]
我是看7.6.2静态库链接  瞎想了一下

**Comment by JessonYue** [comment]
静态链接方式：在程序执行之前完成所有的组装工作，生成一个可执行的目标文件（EXE文件）。
动态链接方式：在程序已经为了执行被装入内存之后完成链接工作，并且在内存中一般只保留该编译单元的一份拷贝。
采用动态链接库的优点：（1）更加节省内存；（2）DLL文件与EXE文件独立，只要输出接口不变，更换DLL文件不会对EXE文件造成任何影响，因而极大地提高了可维护性和可扩展性。
Android 主要是NDK会使用到，可以参看
https://developer.android.google.cn/ndk/guides/standalone_toolchain
