### ISSUE TITLE
为什么生成4字节数字指令会把高位4个字节置为0，生成1字节和2字节数字的指令保持不变？

### ISSUE THREAD

**Issue by 997262600** [JessonYue/Computer-basics#16]
3.4节访问信息里说道：以寄存器作为目标的指令，对于生成小于8字节结果的指令，有两条规则：生成1字节和2字节数字的指令会保持剩下的字节不变；生成4字节数字的指令会把高位4字节置为0。

**Comment by 997262600** [comment]
为什么生成的1字节和2字节的高位没有置为0，只有生成的4字节才置为0？这里的0，是指符号位吗？

**Comment by JessonYue** [comment]
0 不是符号位，在底层开发中 尤其是FPGA的开发，0 是默认的。所以高位需要置地0.

为什么生成的1字节和2字节的高位没有置为0？这句话默认是置0 的，只不过高位一般表示高32bit，这里就不好说高位置0了
