### ISSUE TITLE
《深入理解计算机系统》第二章的内容涉及到很多的概念与计算

### ISSUE THREAD

**Issue by luoqqsh** [JessonYue/Computer-basics#17]
《深入理解计算机系统》第二章的内容涉及到很多的概念与计算，这些是了解为主，还是要吃透，我的读书体会，现在看书是看懂了，到了练习题的时候，还得重温这块内容。感觉一直做不到融会贯通。

**Comment by JessonYue** [comment]
感谢你的反馈。说实话，这本书的题目应该是做的，应该是在大学尤其是大三的时候开始做的，但是我们现在学习，大家比较忙，肯定没时间一道一道做。我建议是：这本书的习题正好答案就在每章节的后面，我建议可以凭着自己的兴趣 选做几道，如果有难度，就直接看下答案。从编码的角度看：

理解浮点数、理解进制转换、字节序（大小端）、位运算、补码运算、数据精度就可以了。（Java程序员基本上平时都不会用到上述知识点）
