### ISSUE TITLE
引用变量存储问题

### ISSUE THREAD

**Issue by Andyaplah** [JessonYue/Computer-basics#19]
java编程思想中,"倘若“将一个对象赋值给另一个对象”，实际是将“引用”从一个地方复制到另一个地方"
我的问题是:
引用变量是栈内存开辟空间,创建对象是在堆内存开辟空间,那么对象中的属性,是引用变量,那么创建对象的时候,对象中的属性(引用变量)是怎么存储的,它会存储在哪里?

**Comment by JessonYue** [comment]
https://www.programcreek.com/2011/11/what-do-java-objects-look-like-in-memory/ 
参考上面的链接和斯坦福的CS143的课 https://web.stanford.edu/class/cs143/

 heap 在heap里面。本质上是一些字节，编译器通过虚表来管理。
