### ISSUE TITLE
《深入理解计算机系统》故障中的加法溢出故障重回当前指令执行会引起故障循环执行吗

### ISSUE THREAD

**Issue by guangzq** [JessonYue/Computer-basics#20]
学科：《深入理解计算机系统》
类型：知识理解
内容：在第八章异常这一章中，第505页，讲到异常的一种类型是“故障”，故障被处理程序处理，并回到原来的指令重新执行，那么像加法溢出这种异常，如果同样如此的话，不就又回到故障了吗，此时程序不就进入不断故障的循环了吗

**Comment by JessonYue** [comment]
你的理解不对。程序是什么？指令+数据 。那么在程序执行的时候，指令出现的了问题，会跳转到对应的异常处理的address来操作，在代码层面。我们可以写c的异常捕获代码，这样程序处理了，还可以回到当前的地方。而加法益处这样的错误，编译器会无法处理的，只能给出异常信息。
