### ISSUE TITLE
从3.2.1章节引发的思考：存储器系统是包含在操作系统内的吗？还是说它们分别是两个不同的系统？虚拟地址是由操作系统创建的还是由处理器创建的，亦或者是什么决定的？

### ISSUE THREAD

**Issue by CWXVashon** [JessonYue/Computer-basics#21]

**Comment by ab503044120** [comment]
操作系统是管理硬件的,存储设备也硬件是属于操作系统管理,包括处理器也是操作系统管理的
![image](https://user-images.githubusercontent.com/5219122/84337905-5622fb80-abcd-11ea-84e0-e42674f42435.png)
虚拟地址是对硬件抽象

**Comment by JessonYue** [comment]
楼上正解
