### ISSUE TITLE
第三章146页，条件预测惩罚浪费的时间在哪？

### ISSUE THREAD

**Issue by slowhandwc** [JessonYue/Computer-basics#22]
条件数据传送和条件控制转移的对比，条件数据传送会计算一个条件操作的两种结果。而条件控制转移会通过条件预测来执行一个分支，预测错误则会从正确的地方开始执行。预测错误会产生条件预测惩罚，这会导致条件控制转移耗费的时间大于条件数据传送。既然在这种情况下两种方式都执行了两个分支，那么为什么条件控制转移耗费的时间要多？条件预测惩罚是否意味着，需要将寄存器和内存的值回滚为之前的值所以耗费了更多的时间？

**Comment by JessonYue** [comment]
我们的处理器通过流水线来获得高性能，流水线的要求就是事先明确要执行的指令顺序。在流水线中，把一条指令分为多个阶段，每个阶段只执行所需操作的一小部分，比如取指令、确定指令类型、读数据、运算、写数据以及更新程序计数器。流水线通过重叠连续指令的步骤来获得高性能，比如在取一条指令的同时，执行它前面指令的算术运算。所以如果事先不知道指令执行顺序，那么事先所做的预备工作就白干了。 为了提高性能，往往可以改写**_使用条件数据传送_**的代码形式提高指令执行效率。

**Comment by JessonYue** [comment]
https://compas.cs.stonybrook.edu/~nhonarmand/courses/sp16/cse502/slides/06-pipelining.pdf 参考下
