### ISSUE TITLE
阅读到 第六章 6.3.1 第424页时,在文中第四节提到缓存管理通过某种东西对存储器进行划分管理

### ISSUE THREAD

**Issue by xiaozongt1989** [JessonYue/Computer-basics#23]
并在文中提到，寄存器中的在不同层级之间传递数据也是依靠这个东西。
通过文中描述，是通过内置缓存中的内置逻辑进行管理的。
但是在查阅资料后，并没有得到，内置逻辑是如何将值在内存中是如何传递的，并且，依然不理解，是如何划分寄存器的层级划分的。

**Comment by ab503044120** [comment]
![image](https://user-images.githubusercontent.com/5219122/84337155-70f47080-abcb-11ea-9f7b-2ab3011e9bef.png)
6.3.1有提到上层是下层的缓存,上层缓存没命中会到下层取数据

**Comment by xiaozongt1989** [comment]
主要是 在文中提到 上层没命中的情况下，下层会提取，提取后会想上层进行一个写的操作，这个操作是怎么进行的呢？
还有 每一个内存层级是怎么进行划分的呢？

**Comment by ab503044120** [comment]
具体看第九章节,在9.6章节有讲操作是如何进行的

**Comment by JessonYue** [comment]
可以忽略，这块可以有个概念即可。
