### ISSUE TITLE
 第二章 2.3.6-2.3.7 整数乘法及除法 

### ISSUE THREAD

**Issue by Leavysong** [JessonYue/Computer-basics#24]
### 时间周期概念
文中提出乘法需要大于等于10个时间周期，那么这里面的时间周期是什么？网上查的话是cpu频率的倒数、单片机的最小时间单位是这个么？为什么说乘法要10个以上除法要30个不太明白怎么来的。。。
### 乘法优化
文中举例 x*14 编译器重写成(x <<3)+(x<<2)+(x<<1)，那么是不是编译器就没有乘法或除法就都是变换成位移和加减法？

**Comment by JessonYue** [comment]
x*14 = x*8 + x*6 =( x<<3 ) + (x<<2) + (x<<1) 这种写法在JDK的源码里面很常见。你的理解是对的。
乘法需要大于等于10个时间周期====》这个具体可以查一下芯片内核指令代码的手册，如果有硬件乘法指令的系统，16位运算与32位运算所用时间，一般是一样的。所以这个和底层的芯片实现有关系，是FPGA的概念。
