### ISSUE TITLE
6.5章节中提及的概念：局部变量存储在寄存器中

### ISSUE THREAD

**Issue by carlwang100** [JessonYue/Computer-basics#25]
- 《深入理解计算机系统》第6.5章节：

路哥，早上好，问一个问题，文中说“**对局部变量的反复引用是友好的，因为编译器可将局部变量存储在寄存器中”**，这句话该怎么去理解？在JVM中，函数在运行阶段会有一个栈帧的概念，栈帧中会有局部变量表，局部变量是保存在局部变量表里面的，然而它是怎么又保存到寄存器中去了，是因为层级不一样吗，反复用到的局部变量就会升级保存到CPU级别的Reg里面去？

**Comment by ab503044120** [comment]
具体看第三章
![image](https://user-images.githubusercontent.com/5219122/84336252-7486f800-abc9-11ea-8e5a-aade9a34c361.png)
如上图可以看到寄存器中有几个可保存局部变量的寄存器
![image](https://user-images.githubusercontent.com/5219122/84336208-60db9180-abc9-11ea-8ba5-8f009734a820.png)
局部变量满足以上几个条件才必须在栈内创建
这个代码才俩局部变量是可以不在栈上创建的
![image](https://user-images.githubusercontent.com/5219122/84336701-6be2f180-abca-11ea-9e0d-abcde95b4678.png)

**Comment by JessonYue** [comment]
很好的思考。C语言中有个变量修饰符就做 register 变量名字。被这个修饰的变量有可能会放到存储器里面，一般CPU会有10多个寄存器，被修饰了会有选择的放入，因为满了就不会放了。所以局部变量会有2个地方。栈和寄存器，只是Java 不怎么偏向底层。所以大家忽略了。
