### ISSUE TITLE
动态链接的问题

### ISSUE THREAD

**Issue by ab503044120** [JessonYue/Computer-basics#26]
学科：《深入理解计算机系统》
类型：知识理解
内容：
1.  第七章  477页  gcc -static 为什么要static  书上解释  -static 参数告诉编译器驱动程序，链接器应该构建一个完全链接的可执行目标文件，它可以加载到内存并运行，在加载时无须更进一步的链.
个人理解: 假如我调用了printf, printf这个函数也会打入可执行文件中.
2. 静态链接时把整个可重定位文件打到可执行文件中,还是只打调用了的 
3.第七章,7.12  489页  位置无关代码
书上写: 现代系统以这样一种方式编译共享模块的代码段，使得可以把它们
加载到内存的任何位置而无需链接器修改。使用这种方法，无限多个进程可以共享一个共
享模块的代码段的单一副本。（当然，每个进程仍然会有它自己的读/写数据块。）
个人理解: 那意思是这个进程加载了so库在其他进程也能用吗,如果是这样 我这个进程修改了so的里面的全局变量 其他进程中的也会被修改呢

4. 个人对静态库和动态库的理解:
静态库链接可以按需加载打入可执行文件中,
动态库在运行时必须得完全加载进内存
这么看来静态库更省内存

**Comment by JessonYue** [comment]
总结一下：gcc -static 打出来的包会很大，因为静态编译会把所有的动态函数和所依赖的任何的东西都打包进去。所以在运行的时候不需要依赖任何的库函数了。你可以写一个pthread_create
的函数，然后gcc -static编译一下。然后通过nm函数进行查询，可以看到在你打包的产物中有很多的函数，这里需要注意一下 有几个标志比如 U：本程序就行调用，没有定义 T：本程序定义
