### ISSUE TITLE
3.7.3 数据传递（栈帧相关问题）

### ISSUE THREAD

**Issue by CWXVashon** [JessonYue/Computer-basics#27]
在x86-64上，当函数传递整型参数大于6个，多出的部分会存放在函数在栈帧分配的空间上，通过栈传递的参数，所有数据大小都向8的倍数对齐。
问题1：这6个整型的6是固定的吗，还是不同的处理器上是不同的？
问题2：数据的大小向8的倍数对齐，如果参数里最大的数据占用8个字节，那么其他也是占用8个字节吗？如果最大的数据占用16字节，是否其他也需要统一的保持一致16字节，又或者说只是8的倍数即可，无需所有参数都是统一大小？

**Comment by ab503044120** [comment]
1. 应该看处理器的x86图如下
![image](https://user-images.githubusercontent.com/5219122/84557384-4cc89900-ad5d-11ea-959b-cf491e986cf8.png)
2. 字节对齐满足下面几个条件
1) 结构体变量的首地址能够被其最宽基本类型成员的大小所整除；
2) 结构体每个成员相对于结构体首地址的偏移量（offset）都是成员大小的整数倍，如有需要编译器会在成员之间加上填充字节（internal adding）；
3) 结构体的总大小为结构体最宽基本类型成员大小的整数倍，如有需要编译器会在最末一个成员之后加上填充字节（trailing padding）

**Comment by JessonYue** [comment]
楼上正解  感谢
