### ISSUE TITLE
牺牲页的问题

### ISSUE THREAD

**Issue by chixiaoliu** [JessonYue/Computer-basics#28]
缺页异常处理器会选择一个牺牲页，这个牺牲页的作用不是太明白。我的理解是缺页时从磁盘拷贝到内存时发现没有空余的页了，然后覆盖一个页数据。这个页就是牺牲页？

**Comment by JessonYue** [comment]
总结：
1、虚拟内存为每个进程提供了一个一致的、私有的地址空间，它让每个进程产生了一种自己在独享主存的错觉（每个进程拥有一片连续完整的内存空间）。
2、牺牲页可以理解成一个中间的缓存页，为啥？因为频繁的从磁盘映射到内存，是非常耗费资源的。为了避免的这样操作，提出了一个牺牲页的概念。相当于懒加载的概念，目前先理解到这个程度。
