### ISSUE TITLE
问题：难道IO设备直接通过IO总线和CPU中寄存器打交道，不需要经过主内存？

### ISSUE THREAD

**Issue by fengbianyun** [JessonYue/Computer-basics#3]
学科：《深入理解计算机系统》
类型：知识理解
内容：该书中1.4. 2 运行 hello 程序有两段描述
1、“'初始时，shell 程序执行它的指令，等待我们输人一个命令。当我们在键盘上输人字符串
./hello后，shell 程序将字符逐一读人寄存器，再把它存放到内存中，”

2、“一旦目标文件 hello 中的代码和数据被加载到主存，处理器就开始执行 hello 程序
的 main 程序中的机器语言指令。这些指令将hello,world/n字符串中的字节从主存
复制到寄存器文件，再从寄存器文件中复制到显示设备，最终显示在屏幕上。”

问题：难道IO设备直接通过IO总线和CPU中寄存器打交道，不需要经过主内存？

**Comment by ab503044120** [comment]
看图1-4

![111111](https://user-images.githubusercontent.com/5219122/83542776-076ec500-a52e-11ea-82aa-79e541e5454e.png)

**Comment by fengbianyun** [comment]
> 看图1-4
> 
> ![111111](https://user-images.githubusercontent.com/5219122/83542776-076ec500-a52e-11ea-82aa-79e541e5454e.png)
要是直接通过IO总线和CPU中的寄存器打交道，为什么还会出现IO速度慢？

**Comment by ab503044120** [comment]
你是说的,高速缓存那一章吗,他是说的主存速度远低于cpu寄存器速度,并没有说io设备速度慢

**Comment by JessonYue** [comment]
这里书籍上讲的原理是 ：计算机原理中的I/O 数据访问。IO设备设备是什么？网卡、存储设备、人机交互设备设备等等。那么这里也会有很多的I/O接口，比如SCSI、串口、并口等等。这里会有I/O数据交互的方式：监控I/O方式，DMA方式等。CPU里面的寄存器就是一个逻辑上的接口，所以可以理解成为主存储器我们绕过了，直接读取寄存器了。学术上的概念可以Google I/O 数据传输。

**Comment by fengbianyun** [comment]
> 这里书籍上讲的原理是 ：计算机原理中的I/O 数据访问。IO设备设备是什么？网卡、存储设备、人机交互设备设备等等。那么这里也会有很多的I/O接口，比如SCSI、串口、并口等等。这里会有I/O数据交互的方式：监控I/O方式，DMA方式等。CPU里面的寄存器就是一个逻辑上的接口，所以可以理解成为主存储器我们绕过了，直接读取寄存器了。学术上的概念可以Google I/O 数据传输。

谢谢，理解了
