### ISSUE TITLE
关联问题

### ISSUE THREAD

**Issue by xiaozongt1989** [JessonYue/Computer-basics#30]
<img width="671" alt="WX20200612-001144@2x" src="https://user-images.githubusercontent.com/12655397/84412495-ea2eaa80-ac41-11ea-9f29-d13260d59e6f.png">
 
是否java中的变量是否与符号解析有关联呢，是否通过C语言进行关联的呢？

**Comment by JessonYue** [comment]
没有。这是2个概念，Java的编译就是JVM虚拟机的那一套，C主要是通过GCC编译，是需要符号解析和符号表的，具体可以看ELF文件的解析中的关于符号表的结构提的定义。symtab 这个struct
