### ISSUE TITLE
为什么64位的计算机可以运行32位计算机编译出来的程序

### ISSUE THREAD

**Issue by JouerRanger** [JessonYue/Computer-basics#31]
在第一章中有讲到，由于不同机器对二进制的程序的处理不同，所以二进制程序是不兼容的，但是为什么64位的计算机可以运行32位计算机编译出来的程序？

**Comment by JessonYue** [comment]
64位的计算机在本质是是位宽是64bit，也就是处理的数据更大，和32的机器在本质上没啥区别。但是64位的OS可能编译的环境和32位的机器是有很大的区别的。这里是2个概念的问题。
