### ISSUE TITLE
signal处理会中断进程,为什么还需要使用异步安全的函数呢

### ISSUE THREAD

**Issue by ab503044120** [JessonYue/Computer-basics#32]
学科：《深入理解计算机系统》
类型：知识理解
内容：第八章 8.55 534页
![image](https://user-images.githubusercontent.com/5219122/84555842-957a5500-ad51-11ea-99b1-1c25956e33b3.png)
既然signal处理函数会中断进程函数,为什么还要使用异步安全函数,变量需要加volidate ,明明不存在并发的可能

**Comment by JessonYue** [comment]
好问题。涉及到中断，信号，线程切换等概念的交换。
中断，一般指的硬件中断，是硬件对cpu的中断。
信号，则是对中断的模拟，可以看作是os对进程的中断。
线程切换，cpu的时分复用手段。、
例如，程序正在调用printf输出，但是在调用printf时，出现了信号，对应的信号处理函数也有printf语句，就会导致两个printf的输出混杂在一起。如果是给printf加锁的话，同样是上面的情况就会导致死锁。对于这种情况，采用的方法一般是在特定的区域屏蔽一定的信号。所以需要异步安全函数。
