### ISSUE TITLE
过程调用中使用的栈是线程独有还是线程共享？

### ISSUE THREAD

**Issue by GeesonLin888** [JessonYue/Computer-basics#34]
第三章中，对于过程调用，是入栈出栈的过程；那这里是否支持多线程同时使用一个栈呢？还是说这个栈是线程独有的？多线程同时操作一个内存，怎么保证线程安全？

**Comment by JessonYue** [comment]
这里问题提的有点问题。不是这么理解的。过程调用是调用linux内核的函数，这个函数用户是无法调用的，但是在底层肯定也存在并发的问题，这个多线层的操作是上层应用需要关注的。可以加锁，队列 、信号等等。
