### ISSUE TITLE
第九章mmap，文件映射，匿名映射的区别，及Android共享内存相关的问题

### ISSUE THREAD

**Issue by foryoung2018** [JessonYue/Computer-basics#35]
文件映射，匿名映射的区别：----------------------------------

![image](https://user-images.githubusercontent.com/29789699/84573925-006d6f80-add6-11ea-8207-b9f77ac07db8.png)

从文章看，我个人认为两者场景的区别：
1、匿名文件会清零所有数据，由内核创建，在子进程和父进程间通信，不知道理解对不？

2、匿名文件没有文件打开关闭，所以更高效?

Android共享内存相关的问题：----------------------------------
1、Android binder驱动使用的内存映射函数 binder_mmap 最终调用的是linux的mmap。
从根本上来说binder通信，使用binder驱动作为共享文件的mmap，这种深层次的理解有问题吗？

2、在学习surfacelinger的时候，经常看到Ashmem匿名共享内存进程间传递数据的使用分析（应该是比较老的资料）。
其实现原理看起来也是调用mmap，只是没有对传递数据的大小像binder使用的限制。
是否可以认为这两种进程间通信的方式殊途同归，其根本实现都是mmap？

**Comment by JessonYue** [comment]
MemoryFile 这个Android的类建议看一看。Android通过Binder传递文件描述符来处理，Android的Binder对于fd的传递也做了适配，原理其实就是在内核层为要传递的目标进程转换fd，因为在linux中fd只是对本进程是有效、且唯一，进程A打开一个文件得到一个fd，不能直接为进程B使用，因为B中那个fd可能压根无效、或者对应其他文件，不过，虽然同一个文件可以有多个文件描述符，但是文件只有一个，在内核层也只会对应一个inode节点与file对象，这也是内核层可以传递fd的基础，Binder驱动通过当前进程的fd找到对应的文件，然后为目标进程新建fd，并传递给目标进程，核心就是把进程A中的fd转化成进程B中的fd。注意一点：匿名共享内存不会占用Dalvik Heap与Native Heap，不会导致OOM。这是优点。
=====关于mmap======：
mmap属于系统调用，用户控件间接通过swi指令触发软中断，进入内核态（各种环境的切换），进入内核态之后，便可以调用内核函数进行处理。mmap是一种内存映射文件的方法，即将一个文件或者其它对象映射到进程的地址空间，实现文件磁盘地址和进程虚拟地址空间中一段虚拟地址的一一对映关系。相比read（），mmap也就是少了内存的copy，也就一次pagefault。
