### ISSUE TITLE
深入理解计算机系统第八章8.2.4关于用户模式和内核模式的问题(p510)

### ISSUE THREAD

**Issue by HaoWangCold** [JessonYue/Computer-basics#36]
在书的8.2.4 用户模式和内核模式中提到当设置模式位的时候，进程享有内核模式，如果没有设置，则为用户模式。那么这两个模式在Linux下会共存吗？ 
在 Android 系统中存在 gid(group id) 和 uid（user id）用来管理权限，感觉这两个和书中提到的内核模式和用户模式有相通的地方，但好像就有不太一样，那这两对概念有什么相同点和不同点，可以混为一谈吗？

**Comment by JessonYue** [comment]
内核/用户模式切换是通过使用软件中断处理程序来实现的，该中断处理程序可以脱离线程保护环，但实现为仅在内核空间中执行，然后返回到用户空间，特别是执行该操作的用户空间进程。所以书上说的是通过中断来保持内核和用户态的切换，特别是进程在切换上下文的时候。

Android中的 gid(group id) 和 uid（user id）用来管理权限，是从软件的层面出发，我们知道linux有用户权限的，所以你说的是2个层面的东西。
