### ISSUE TITLE
小端法的意义

### ISSUE THREAD

**Issue by slowhandwc** [JessonYue/Computer-basics#5]
既然大端法更符合人类阅读的习惯，那为什么还会有小端法？是为了效率麽？

**Comment by JessonYue** [comment]
大小端和CPU有关系，本质上字节序的概念。这取决与CPU厂家的实现方式。

**Comment by zpjsmalltime** [comment]
规范问题吧，大端小端历来都互相争论，只要发送者和接受者协定好就行了吧。书中是这个意思。
