### ISSUE TITLE
JVM的主内存跟物理硬件上的主内存是一个概念吗？

### ISSUE THREAD

**Issue by foryoung2018** [JessonYue/Computer-basics#6]
![image](https://user-images.githubusercontent.com/29789699/83602008-493a5280-a5a4-11ea-9a20-74b0ba3c60d9.png)
![image](https://user-images.githubusercontent.com/29789699/83602072-71c24c80-a5a4-11ea-898d-2ada922b3be8.png)

**Comment by JessonYue** [comment]
http://tutorials.jenkov.com/java-concurrency/java-memory-model.html  可以读一读这篇文章。
几个概念：
1.JVM内存模型和JMM(Java内存模型)不是一回事。
2.主内存就是电脑的RAM，计算机组成原理里面，RAM就是主存，而工作内存就是指JVM开辟出来的内存，也就是运行时数据区。
3.JMM是讲线程的，它是讲线程如何处理数据的，JMM的工作内存和主内存是非物理的内存区域。
4.JVM的的主内存可以理解成RAM。

**Comment by ab503044120** [comment]
jvm是一个进程,进程的虚拟内存中有一部分是来自主存(RAM)的,jvm内存模型是在虚拟内存中再去划分的.
jmm的工作内存在线程运行时会从(某个地方)加载到高速缓存中,在被切换后应该会存到jvm的(某个地方),jmm的主存是指的jvm的堆中的数据

我的理解不知道真确否
有个问题(某个地方)是jvm的哪个地方呢 @JessonYue

**Comment by foryoung2018** [comment]
> http://tutorials.jenkov.com/java-concurrency/java-memory-model.html 可以读一读这篇文章。
> 几个概念：
> 1.JVM内存模型和JMM(Java内存模型)不是一回事。
> 2.主内存就是电脑的RAM，计算机组成原理里面，RAM就是主存，而工作内存就是指JVM开辟出来的内存，也就是运行时数据区。
> 3.JMM是讲线程的，它是讲线程如何处理数据的，JMM的工作内存和主内存是非物理的内存区域。
> 4.JVM的的主内存可以理解成RAM。
多谢路哥，文章讲得很明确，jmm的主内存工作内存都有可能分配在RAM，CPU CACHED, register里面。

**Comment by foryoung2018** [comment]
> jvm是一个进程,进程的虚拟内存中有一部分是来自主存(RAM)的,jvm内存模型是在虚拟内存中再去划分的.
> jmm的工作内存在线程运行时会从(某个地方)加载到高速缓存中,在被切换后应该会存到jvm的(某个地方),jmm的主存是指的jvm的堆中的数据
> 
> 我的理解不知道真确否
> 有个问题(某个地方)是jvm的哪个地方呢 @JessonYue




多谢路哥，文章讲得很明确，jmm的主内存工作内存都有可能分配在RAM，CPU CACHED, register里面。

**Comment by foryoung2018** [comment]
> http://tutorials.jenkov.com/java-concurrency/java-memory-model.html 可以读一读这篇文章。
> 几个概念：
> 1.JVM内存模型和JMM(Java内存模型)不是一回事。
> 2.主内存就是电脑的RAM，计算机组成原理里面，RAM就是主存，而工作内存就是指JVM开辟出来的内存，也就是运行时数据区。
> 3.JMM是讲线程的，它是讲线程如何处理数据的，JMM的工作内存和主内存是非物理的内存区域。
> 4.JVM的的主内存可以理解成RAM。


多谢路哥，文章讲得很明确，jmm的主内存工作内存都有可能分配在RAM，CPU CACHED, register里面。

closed
