### ISSUE TITLE
《深入理解计算机系统》第二章2.3.3 补码的非——加法的逆

### ISSUE THREAD

**Issue by xt4665699** [JessonYue/Computer-basics#9]
学科：《深入理解计算机系统》
类型：知识理解
内容：第二章2.3.3 补码的非中提到加法的逆，加法的逆这个概念没明白说的是什么意思，是相反吗？
![image](https://user-images.githubusercontent.com/19283693/83624513-4e5bc980-a5c5-11ea-9c7c-fee4f70ed6af.png)

**Comment by JessonYue** [comment]
2种方法： 补码的非 就是  取反+1    在C语言中    -x=～x+1 

还有一种就是   【1100】==》【0100】-4 取反 4 
 【1000】===》 【1000】-8 取反 8
